@echo off
:: ** Script generated by Reporting Services Scripter 2.0.0.17 **
:: ** Created by Jasper Smith (jas@sqldbatips.com)             **
:: ** See http://www.sqldbatips.com for help/support           **

::Script Variables
SET LOGFILE="RS Scripter Load Log.txt"
SET SCRIPTLOCATION=
SET BACKUPLOCATION=
SET REPORTSERVER=http://localhost/ReportServer
SET RS="C:\Program Files\Microsoft SQL Server\100\Tools\Binn\RS.EXE"
SET TIMEOUT=60

::Clear Log file
IF EXIST %logfile% DEL %logfile%

::Write Log Header
ECHO Reporting Services Scripter Load Log 2.0.0.17 >>%LOGFILE%
ECHO. >>%LOGFILE%
ECHO Starting Load at %DATE% %TIME% >>%LOGFILE%
ECHO SCRIPTLOCATION = %SCRIPTLOCATION% >>%LOGFILE%
ECHO REPORTSERVER   = %REPORTSERVER% >>%LOGFILE%
ECHO BACKUPLOCATION = %BACKUPLOCATION% >>%LOGFILE%
ECHO SCRIPTLEVEL    = SQL2008 >>%LOGFILE%
ECHO TIMEOUT        = %TIMEOUT% >>%LOGFILE%
ECHO RS             = %RS% >>%LOGFILE%
ECHO. >>%LOGFILE%

::Run Scripts

ECHO Running script "%SCRIPTLOCATION%Reports\Reports.fldr.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Reports.fldr.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\RPTDS.rds.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\RPTDS.rds.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\AccessRightsReport.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\AccessRightsReport.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ADV_TR_Balance.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ADV_TR_Balance.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ADV_TR_Balance_Ver2.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ADV_TR_Balance_Ver2.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ADV_TR_Balance_Ver2_1.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ADV_TR_Balance_Ver2_1.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\AreaBillView.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\AreaBillView.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Balance Sheet.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Balance Sheet.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\BILL_Entry.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\BILL_Entry.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register_bkp.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register_bkp.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register_Ritco.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register_Ritco.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register_Ritco_bkp.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register_Ritco_bkp.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register_Ver2.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register_Ver2.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Bill_Register_ver2_1.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Bill_Register_ver2_1.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\CBS.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\CBS.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\CBS_Ver1.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\CBS_Ver1.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\CHQ_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\CHQ_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\CHQ_Register_Popup_Usage.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\CHQ_Register_Popup_Usage.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Contract_View.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Contract_View.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\CustomerContractView.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\CustomerContractView.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DEL_SUMMARY.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DEL_SUMMARY.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT_FLOW_REGISTER.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT_FLOW_REGISTER.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT_FLOW_Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT_FLOW_Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT_Prof.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT_Prof.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT_Prof_Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT_Prof_Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DKT_Summary_TAB.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DKT_Summary_TAB.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Doc_Yet_To_Scan.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Doc_Yet_To_Scan.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DOCKET_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DOCKET_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Docket_Movement_Report.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Docket_Movement_Report.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\DRS_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\DRS_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\EXP_REG_PDC.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\EXP_REG_PDC.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\EXP_REG_THC.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\EXP_REG_THC.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ExpectedArrival.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ExpectedArrival.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Fin_life_cycle.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Fin_life_cycle.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\General_Ledger.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\General_Ledger.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\GenLedger.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\GenLedger.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\GENLedger_TYPWise.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\GENLedger_TYPWise.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\GL_Ver1.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\GL_Ver1.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\INSRPT.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\INSRPT.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\LRWiseCollectionRegister.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\LRWiseCollectionRegister.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\LS_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\LS_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\LsMf.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\LsMf.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\MarketVehicle_SSRS.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\MarketVehicle_SSRS.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\MF_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\MF_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Miss_Route_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Miss_Route_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Movement_TAB.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Movement_TAB.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Movement_TAB_THC.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Movement_TAB_THC.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\MR_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\MR_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\OPN_LIFE_CYCLE.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\OPN_LIFE_CYCLE.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\OPN_LIFE_CYCLE_DET.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\OPN_LIFE_CYCLE_DET.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\OPN_LIFE_TAB.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\OPN_LIFE_TAB.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\OUTSTD.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\OUTSTD.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\OUTSTD_BKP.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\OUTSTD_BKP.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\POD_PFM.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\POD_PFM.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Profit_loss_TAB.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Profit_loss_TAB.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ProfitLoss.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ProfitLoss.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\PRS_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\PRS_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\ReportAccessRights_Report.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\ReportAccessRights_Report.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Sales Dashboard.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Sales Dashboard.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Sales Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Sales Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Sales_Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Sales_Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\SalesRegister_Test.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\SalesRegister_Test.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Salse Profitability.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Salse Profitability.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Salse Profitability Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Salse Profitability Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Service_Level.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Service_Level.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\STAX_COLL_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\STAX_COLL_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\STAX_REG_VER1.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\STAX_REG_VER1.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\STAX_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\STAX_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Stock Report.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Stock Report.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Stock_Report_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Stock_Report_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Stock_Report_Register_old.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Stock_Report_Register_old.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Stock_Report_Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Stock_Report_Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\TDS_Register.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\TDS_Register.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\THC_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\THC_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\TimeTracking.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\TimeTracking.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Tracking_THC_Summary.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Tracking_THC_Summary.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\TRBALANCE.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\TRBALANCE.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\TUR_VIEW.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\TUR_VIEW.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Vehicle_Movement_Report.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Vehicle_Movement_Report.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\VehicleUnloadingRegister.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\VehicleUnloadingRegister.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\VUR_Details.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\VUR_Details.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO Running script "%SCRIPTLOCATION%Reports\Work_Done_Report.rdl.rss" >>%LOGFILE%
%RS% -i "%SCRIPTLOCATION%Reports\Work_Done_Report.rdl.rss" -s %REPORTSERVER% -l %TIMEOUT% -v BACKUPLOCATION="%BACKUPLOCATION%" >>%LOGFILE% 2>&1
ECHO. >>%LOGFILE%

ECHO. >>%LOGFILE%
ECHO Finished Load at %DATE% %TIME% >>%LOGFILE%
ECHO. >>%LOGFILE%
