<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Bill_Summ_RptPopup.aspx.cs" Inherits="GUI_UNI_MIS_Bill_Summary_Bill_Summ_RptPopup" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <link href="../../../GUI/images/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div><center class ="blackfnt">
        Bill View for :<asp:Label ID="lblBill_No" runat="server" CssClass="blackfnt"></asp:Label><br />
        <br />
        <br />
        <table border="0" cellpadding="2" cellspacing="1" style="background-color: #cc00ff"
            width="75%">
            <tr class="bgbluegrey">
                <td align="center" class="blackfnt" colspan="4" style="height: 20px">
                    <label id="Label5" class="blackfnt">
                        Bill View</label></td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt" style="height: 23px">
                    <label id="Label6" class="blackfnt">
                        Bill Generation Date</label></td>
                <td align="left" class="blackfnt">
                    <%=BillGenDate%>
                </td>
                <td align="left" class="blackfnt" style="height: 23px">
                    Billing Branch</td>
                <td align="left" class="blackfnt">
                  <%=BillBranch%>   
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                    <label id="Label7" class="blackfnt">
                        Bill Submission Date</label></td>
                <td align="left" class="blackfnt">
                    <%=BillSubDate%>
                </td>
                <td align="left" class="blackfnt">
                    Bill Type</td>
                <td align="left" class="blackfnt">
                  <%=BillType%>     
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt" style="height: 20px">
                    Bill Due Date</td>
                <td align="left" class="blackfnt" style="height: 20px">
                <%=BillDueDate%>
                </td>
                <td align="left" class="blackfnt" style="height: 20px">
                    Party Code and Name</td>
                <td align="left" class="blackfnt" style="height: 20px">
                   <%=PartyCode%> 
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                    Bill Collection Date</td>
                <td align="left" class="blackfnt">
                  <%=BillCollDate%>   
                </td>
                <td align="left" class="blackfnt">
                    Party Address</td>
                <td align="left" class="blackfnt">
                    <%=PartyAdd%>  
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                </td>
                <td align="left" class="blackfnt">
                </td>
                <td align="left" class="blackfnt">
                    Party Phone Number</td>
                <td align="left" class="blackfnt">
                <%=PartyPhone%>   
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                    </td>
                <td align="left" class="blackfnt">
                </td>
                <td align="left" class="blackfnt">
                    Party E-mail</td>
                <td align="left" class="blackfnt" style="height: 20px">
                 <%=PartyMail%>   
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                    Bill Generated By</td>
                <td align="left" class="blackfnt">
                <%=BillGenBy%>
                </td>
                <td align="left" class="blackfnt">
                    Bill Submitted By</td>
                <td align="left" class="blackfnt" style="height: 20px">
                <%=BillSubBy%>
                </td>
            </tr>
            <tr style="background-color: #ffffff">
                <td align="left" class="blackfnt">
                    Bill Collected By</td>
                <td align="left" class="blackfnt">
                <%=BillCollBy%>
                </td>
                <td align="left" class="blackfnt">
                    Bill Close By</td>
                <td align="left" class="blackfnt" style="height: 20px">
                <%=BillClose%>
                </td>
            </tr>
        </table>
        <br />
        <br />
           <table border="0" style="width: 98%; background-color: #808080" align="center" cellspacing="1" cellpadding="2" class="boxbg">
       
        <tr class="bgbluegrey"><td style="width: 5%; height: 25px;"><label class="blackfnt">Sr. No</label></td>
       
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Docket No</label></td>
       
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Booking Branch</label></td>
       
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Delivery Branch</label></td>
               
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Docket Date</label></td>
        
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Commited Delivery Date</label></td>
        
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Actual Delivery Date</label></td>

        <td style="width: 9%; height: 25px;"><label class="blackfnt">Charged Weight</label></td>
        
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Docket Amount</label></td>
        
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Service Tax</label></td>
        
        <td style="width: 9%; height: 25px;"><label class="blackfnt">Docket Total</label></td>        
                                                                        
        </tr>
        
        <asp:Repeater ID="rptBillDetails" runat="server">
        
        <ItemTemplate>
        
                <tr style="background-color: White">
                    <td style="width: 198px"><center>
                        <label class="blackfnt">
                            <%#DataBinder.Eval(Container.DataItem, "RowCounter")%>
                        </label></center>
                    </td>
                    <td>
                        <label class="blackfnt">
                                <%#DataBinder.Eval(Container.DataItem, "DocNo")%>                        
                        </label>
                    </td>                                     
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "BookBranch")%>                           
                        </label></center>
                    </td>
                    
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "Delivery")%>                            
                        </label></center>
                    </td>
                 <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "DocDate")%>     
                        </label></center>
                    </td>
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "CommDate")%>                             
                        </label></center>
                    </td>
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "ActualDate")%>  
                        </label></center>
                    </td>                                                                           
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "ChrgWeight")%>                            
                        </label></center>
                    </td>
                      <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "DocAmt")%>   
                        </label></center>
                    </td>
                      <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "SevTax")%>                            
                        </label></center>
                    </td>   
                    <td><center>
                        <label class="blackfnt">
                        <%#DataBinder.Eval(Container.DataItem, "DocTotal")%>   
                        </label></center>
                    </td>                                    
                </tr>
            </ItemTemplate>
        </asp:Repeater> 
        <tr style="background-color: #FFFFFF" runat="server" id="trForTotalValues"> 
                                                                        <td colspan="8" align="right">
                                                                            <label class="blackfnt">
                                                                                <b>
                                                                                    Total :
                                                                                </b>
                                                                            </label>
                                                                        </td>
                                                                            
                                                                           <td><center>
                                                                            <asp:Label cssclass="blackfnt" ID="lblDocAmt" runat="server" Font-Bold="true">
                                                                            </asp:Label></center>
                                                                        </td>                                                                        
                                                                        <td><center>
                                                                            <asp:Label cssclass="blackfnt" ID="lblSerTax" runat="server" Font-Bold="true">
                                                                            </asp:Label></center>
                                                                        </td>                                                                        
                                                                        <td><center>
                                                                            <asp:Label cssclass="blackfnt" ID="lblDocTotal" runat="server" Font-Bold="true">
                                                                            </asp:Label></center>
                                                                        </td>                                                                          
                                                                    </tr>            
    </table>
    <table id="tblNoRecords" runat="server" border="0" style="width: 98%; background-color: #808080" 
                                                                    align="center" cellspacing="1" cellpadding="2" class="boxbg" visible="false">
                                                                    <tr style="background-color: #ffffff">
                                                                        <td colspan="22" align="right" style="width: 892px; height: 23px;">
                                                                            <div align="center">
                                                                                <label style="color: #FF0000;" class="blackfnt">
                                                                                    No Record Found
                                                                                </label>
                                                                            </div>
                                                                        </td>
                                                                    </tr>
                                                                    </table>
    </center>
    
    </div>
    </form>
</body>
</html>
