<%@ Page Language="C#" MasterPageFile="~/GUI/MasterPage.master" AutoEventWireup="true" CodeFile="AdviceView.aspx.cs" Inherits="GUI_Finance_advice_AdviceView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MyCPH1" Runat="Server">
    <br />
    <asp:Label ID="lbl_Voucher_Header" runat="server" CssClass="blackfnt" Font-Bold="true" style="left:50;">Advice</asp:Label>
    <br />
    <br />
    <table class="boxbg" bgcolor="#808080" border="0" cellpadding="3" cellspacing="1" style="width:9in;">
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left" width="20%">Advice No</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" width="30%"><asp:Label ID="lbl_Advice_No" runat="server" Text=""></asp:Label></td>
            <td class="bgbluegrey" align="left" width="20%">Advice Type</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" width="30%"><asp:Label ID="lbl_Advice_Type" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Advice Date</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Advice_Date" runat="server" Text=""></asp:Label></td>
            <td class="bgbluegrey" align="left">Generated By</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Generated_By" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Raised By</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Raised_By" runat="server" Text=""></asp:Label></td>
            <td class="bgbluegrey" align="left">Raised on Branch</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Raised_on_Branch" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Reason</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" colspan="3"><asp:Label ID="lbl_Reason" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Enclosed Documents</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" colspan="3"><asp:Label ID="lbl_Enclosed_Documents" runat="server" Text=""></asp:Label></td>
        </tr>
    </table>
    <br />
    <table class="boxbg" bgcolor="#808080" border="0" cellpadding="3" cellspacing="1" style="width:9in;">
        <tr class="blackfnt">
            <td class="blackfnt" bgcolor="#ffffff" align="center" colspan="4">
                <asp:Label ID="lbl_Payment_Details" runat="server" CssClass="blackfnt" Font-Bold="true">Payment Details</asp:Label>
            </td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left" width="20%">Mode Of Transaction</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" width="30%"><asp:Label ID="lbl_Mode_Of_Transaction" runat="server" Text=""></asp:Label></td>
            <td class="bgbluegrey" align="left" width="20%">Cash / Bank Account</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" width="30%"><asp:Label ID="lbl_Cash_Bank_Account" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Cheque Number</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Cheque_Number" runat="server" Text=""></asp:Label></td>
            <td class="bgbluegrey" align="left">Cheque Date</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left"><asp:Label ID="lbl_Cheque_Date" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="bgbluegrey" align="left">Payment Amount</td>
            <td class="blackfnt" bgcolor="#ffffff" align="left" colspan="3"><asp:Label ID="lbl_Payment_Amount" runat="server" Text=""></asp:Label></td>
        </tr>
        <tr class="blackfnt">
            <td class="blackfnt" bgcolor="#ffffff" align="left" colspan="4"><asp:Label ID="lbl_In_Words" runat="server" Text=""></asp:Label></td>
        </tr>
    </table>
    <br />
    <br />
    <table class="boxbg" bgcolor="#808080" border="0" cellpadding="3" cellspacing="1" style="width:9in;">
        <tr class="blackfnt">
            <td class="blackfnt" bgcolor="#ffffff" align="left">Passing Authority</td>
            <td class="blackfnt" bgcolor="#ffffff" align="center">Cashier/Acc</td>
            <td class="blackfnt" bgcolor="#ffffff" align="right">Manager/Director</td>
        </tr>
    </table>  
    <br />
    <br />
    <font class="blackfnt">ENCLOSE ALL SUPPORTING DOCUMENT</font>
    <br />
    <br />
    <font class="blackfnt">Signature</font>
    <br />
</asp:Content>
